name: Run checks
on: [push]
jobs:
  client-check-svelte:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install-test
        working-directory: ./client
      - name: Run checks
        run: pnpm check
        working-directory: ./client
      - name: Build
        run: pnpm build
        working-directory: ./client
  fake-server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install-test
        working-directory: ./fake-server
      - name: Run tests
        run: pnpm test
        working-directory: ./fake-server
